version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gaja-menu-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gaja
      POSTGRES_PASSWORD: gaja_password_2024
      POSTGRES_DB: gaja_menu
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
